CREATE TABLE all_medication_dispensing
(
dispensing_id       varchar(50),
form                varchar(10),  
patient_id          varchar(50),  
emr_id              varchar(50),  
encounter_id        varchar(50),  
encounter_datetime  datetime,     
encounter_location  varchar(255), 
datetime_entered    datetime,     
user_entered        text,  
encounter_provider  text,  
drug_name           varchar(255), 
drug_openboxes_code int,          
duration            int,          
duration_unit       varchar(255),  
quantity_per_dose   float,        
dose_unit           varchar(255),  
frequency           varchar(255),  
quantity_dispensed  int,          
quantity_unit       varchar(255),  
order_id            varchar(50),
instructions        text,         
index_asc           int,          
index_desc          int           
);
