CREATE TABLE all_lab_orders
(
 patient_id                   VARCHAR(100),  
 emr_id                       VARCHAR(50),   
 wellbody_emr_id              VARCHAR(255),  
 kgh_emr_id                   VARCHAR(255),  
 order_visit_id               VARCHAR(50),   
 order_encounter_id           VARCHAR(50),   
 loc_registered               VARCHAR(255),  
 unknown_patient              CHAR(1),       
 gender                       CHAR(1),       
 age_at_encounter             INT,           
 patient_address              VARCHAR(1000), 
 order_number                 VARCHAR(255),  
 accession_number             VARCHAR(255),  
 orderable                    VARCHAR(255),  
 status                       VARCHAR(255),  
 user_entered                 VARCHAR(255),  
 orderer_provider_type        VARCHAR(255),  
 order_datetime               DATETIME,      
 ordering_location            VARCHAR(255),  
 urgency                      VARCHAR(255),  
 specimen_collection_datetime DATETIME,      
 collection_date_estimated    VARCHAR(255),  
 test_location                VARCHAR(255),  
 results_date                 DATETIME       
);
