CREATE TABLE all_medications_prescribed
(
    medication_prescription_id  varchar(25),
    order_id                    varchar(25),
    obs_id                      varchar(25),
    encounter_id                varchar(25),
    visit_id                    varchar(25),
    patient_id                  varchar(25),
    emr_id                      varchar(25),
    order_type                  varchar(30),
    order_location              varchar(255),
    date_entered                date,
    order_date_activated        date,
    expiration_datetime         datetime,
    user_entered                varchar(255),
    prescriber                  varchar(255),
    order_drug                  varchar(255),
    order_formulation           varchar(255),
    order_formulation_non_coded text,
    product_code                varchar(50),
    order_quantity              float,
    order_quantity_units        varchar(50),
    order_quantity_num_refills  int,
    order_dose                  int,
    order_dose_unit             varchar(50),
    order_dosing_instructions   text,
    order_route                 varchar(50),
    order_frequency             varchar(50),
    order_duration              int,
    order_duration_units        varchar(50),
    order_reason                text,
    order_comments              text,
    quantity_dispensed          int,
    dispensing_status           varchar(255),
    status_reason               varchar(255),
    refills_remaining           int,
    index_asc                   int,
    index_desc                  int
)
;
