CREATE TABLE mch_maternity_form
(
emrid varchar(30),
provider varchar(30),
location varchar(30),
form_date date,
delivery_date date,
estimated_delivery_date date, -- NULL 
gestational_age int, -- NULL 
birth_weight float,
estimated_blood_loss float,
delivery_type bit, -- NOT available 
vaginal_delivery bit,
breech bit,
perineal_tear varchar(50),
apgar_score_onemin varchar(50),
apgar_score_5min int,
apgar_score_10min varchar(50),
GBV_victim bit,
chorioamnionitis bit,
severe_preeclampsia bit,
eclampsia bit,
prolonged_labor bit,
acute_pulmonary_edema bit,
puerperal_sepsis bit,
herpes_simplex bit,
syphilis bit,
other_STI bit,
other bit,
other_free_response varchar(100),
postpartum_hemorrhage bit,
blood_loss varchar(10),
placental_abnormality bit,
malpresentation_fetus bit,
cephalopelvic_disproportion bit,
lbw_1000_1249 bit,
lbw_1250_1499 bit,
lbw_1500_1749 bit,
lbw_1750_1999 bit,
lbw_2000_2499 bit,
extreme_premature_less_28 bit,
very_premature_28_32 bit,
moderate_prematurity_33_36 bit,
respiratory_distress bit,
birth_asphyxia bit,
fetal_distress bit,
intrauterine_fetal_demise bit,
intrauterine_growth_retardation bit,
congenital_malformation bit,
premature_rupture_membranes bit,
meconium_aspiration bit,
exit_date date,
presumed_or_confirmed_diagnosis varchar(100),
clinical_note varchar(500),
primary_diagnosis bit,
confirmed_diagnoses bit,
counselled_HIV_testing varchar(100),
med_name  varchar(100),
med_dose  varchar(10),
med_dose_unit  varchar(100),
med_route  varchar(100),
med_freq  varchar(100),
med_duration  varchar(100),
med_duration_unit  varchar(100),
med_admin_instructions  varchar(500)
);