create table mch_labor_summary_encounter
(
    encounter_id                            varchar(100),
    visit_id                                varchar(100),
    patient_id                              varchar(100),
    emr_id                                  varchar(255),
    pregnancy_program_id                    varchar(100),
    encounter_datetime                      datetime,
    encounter_location                      varchar(255),
    datetime_entered                        datetime,
    user_entered                            varchar(255),
    provider                                varchar(255),
    age_at_encounter                        int,
    labor_start                             datetime,
    induced_labor                           bit,
    induction_time                          datetime,
    method_of_induction                     varchar(255),
    duration_first_stage                    decimal(8, 3),
    second_stage_start                      datetime,
    duration_second_stage                   decimal(8, 3),
    multiple_birth                          bit,
    amtsl                                   bit,
    visual_inspection_placenta_completeness varchar(255),
    birth_attendant                         varchar(255),
    perineal_tear                           varchar(255),
    perineal_tear_procedure                 varchar(255),
    duration_third_stage                    decimal(8, 3),
    total_duration_labor                    int,
    partogram_uploaded                      bit,
    index_asc                               INT,
    index_desc                              INT
);
