create table mch_newborn_assessment_encounter
(
    encounter_id             varchar(100),
    visit_id                 varchar(100),
    patient_id               varchar(100),
    emr_id                   varchar(255),
    encounter_datetime       datetime,
    encounter_location       varchar(255),
    datetime_entered         datetime,
    user_entered             varchar(255),
    provider                 varchar(255),
    pregnancy_complications  varchar(5000),
    delivery_datetime        datetime,
    gestational_age          decimal(8, 3),
    delivery_type            varchar(255),
    delivery_outcome         varchar(255),
    sex                      varchar(255),
    birth_weight             decimal(8, 3),
    birth_length             decimal(8, 3),
    birth_head_circumference decimal(8, 3),
    apgar_1_min              int,
    apgar_5_min              int,
    apgar_10_min             int,
    multiple_birth           bit,
    temperature              int,
    heart_rate               int,
    bp_systolic              int,
    bp_diastolic             int,
    respiratory_rate         int,
    o2_saturation            int,
    neonatal_resuscitation   bit,
    resuscitation_type       varchar(255),
    diagnosis_at_birth       varchar(255),
    birth_injury             bit,
    overall_condition        varchar(255),
    disposition              varchar(255),
    transfer_location        varchar(255),
    death_date               datetime,
    index_asc                INT,
    index_desc               INT
);
