create table newborn_progress_discharge_encounter
(
    encounter_id        varchar(100),
    visit_id            varchar(100),
    patient_id          varchar(100),
    emr_id              varchar(255),
    encounter_datetime  datetime,
    encounter_location  varchar(255),
    datetime_created    datetime,
    user_entered        varchar(255),
    provider            varchar(255),
    visit_type          varchar(255),
    rbg                 decimal(8, 3),
    umbilical_cord      varchar(255),
    eyes                varchar(255),
    skin_color          varchar(255),
    urination           varchar(255),
    stool               varchar(255),
    feeding_method      varchar(255),
    weight              decimal(8, 3),
    temperature         int,
    heart_rate          int,
    eye_drops           bit,
    umbilical_cord_care bit,
    vitamin_k           bit,
    disposition         varchar(255),
    transfer_location   varchar(255),
    death_date          datetime,
    index_asc           INT,
    index_desc          INT
);