CREATE TABLE pregnancy_program
(
    pregnancy_program_id            varchar(25),
    patient_id                      varchar(25),
    emr_id                          varchar(30),
    reg_location                    varchar(255),
    date_enrolled                   date,
    date_completed                  date,
    outcome                         varchar(255),
    current_state                   varchar(255),
    pregnancy_status                varchar(255),
    birthdate                       date,
    age_at_pregnancy_registration   int,
    danger_signs                    varchar(1000),
    high_risk_factors               varchar(1000),
    estimated_gestational_age       varchar(10),
    estimated_delivery_date         date,
    actual_delivery_date            date,
    delivery_location               varchar(255),
    delivery_outcome                varchar(255),
    number_of_fetuses               int,
    hiv_status                      varchar(255),
    trimester_enrolled              varchar(255),
    total_anc_visits                int,
    iptp_sp_malaria_ever            bit,
    nutrition_counseling_ever       bit,
    hiv_counsel_and_test_ever       bit,
    insecticide_treated_net_ever    bit,
    iron_ifa_ever                   bit,
    syphilis_test_ever              bit,
    arv_for_pmtct                   bit,
    muac_measured                   bit,
    anc_visit1_weight_recorded      bit,
    malaria_treatment_during_antenatal bit,
    index_asc                       int,
    index_desc                      int
);
