CREATE TABLE pregnancy_program
(pregnancy_program_id   varchar(50),  
emr_id                varchar(30),  
patient_id            varchar(50),  
reg_location          varchar(255), 
date_enrolled         date,         
date_completed        date,         
outcome               varchar(255), 
current_state         varchar(255), 
anc_start_date        date,         
anc_end_date          date,         
postpartum_start_date date,         
postpartum_end_date   date,         
index_asc             int,          
index_desc            int);         
