name: Build SL ETL using mvn
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Run maven clean install
        run: mvn clean install

  release:
    runs-on: ubuntu-latest
    needs: build

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
      - name: Publish package
        run: mvn clean deploy -U -DdeployRelease -Dgpg.passphrase=${server-username} -Dgpg.keyname=${server-password}
