name: Build SL ETL using mvn
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Run maven clean install
        run: mvn clean install

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      - name: Publish package
        run: mvn clean deploy -U -DdeployRelease -Dgpg.passphrase=${secrets.OSS_SERVER_USERNAME} -Dgpg.keyname=${secrets.OSS_SERVER_PSWD}
